import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  c1550M10_5SourceReviewSchema,
  M10_5_SOURCE_REVIEW_FEATURE_IDS,
} from '../src/data/temporalSchema'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = resolve(repositoryRoot, 'data/research/c1550/m10.5-source-review.json')

const tranche = c1550M10_5SourceReviewSchema.parse({
  schema_version: 1,
  milestone: 'M10.5',
  tranche: 'source-review-1',
  period_id: 'c1550',
  status: 'ready_for_content_review',
  public_application_import: false,
  updated_on: '2026-10-02',
  scope_note: 'Diez fichas bilingües preparadas desde fuentes iniciales para revisión de contenido; ninguna crea ni promociona geometría c. 1550.',
  feature_ids: M10_5_SOURCE_REVIEW_FEATURE_IDS,
  items: [
    {
      feature_id: 'commerce.corral-carbon',
      cluster: 'civic_centre',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'converted', physical_state: 'complete',
      },
      content: localized(
        'Corral de comedias (antigua Alhóndiga Nueva)',
        'Corral de comedias dentro de un funduq nazarí reutilizado',
        'El antiguo funduq seguía materialmente presente, pero tras la subasta de 1531 pasó a funcionar como corral de comedias, mostrando una conversión de uso sin demolición del edificio.',
        'La secuencia de propiedad y uso está documentada; la distribución teatral hacia 1550 y las adaptaciones materiales concretas aún no justifican una nueva planta.',
        'Desde 1492 el alojamiento y comercio del funduq cedieron ante usos cristianos y teatrales, conservándose la estructura principal heredada.',
        'Playhouse (former New Corn Exchange)',
        'Playhouse inside a reused Nasrid funduq',
        'The former funduq remained materially present, but after the 1531 auction it became a playhouse, demonstrating conversion of use without demolition of the building.',
        'The ownership and use sequence is documented; the theatrical arrangement around 1550 and its specific material adaptations do not yet support a new plan.',
        'After 1492 the funduq’s lodging and commercial roles gave way to Christian and theatrical uses while its main inherited structure survived.',
      ),
      claims: [
        claim('claim.corral-carbon-theatre-1531', 'transformation',
          'Tras la subasta de 1531 la antigua alhóndiga pasó a ser corral de comedias.',
          'After the 1531 auction the former corn exchange became a playhouse.',
          'source.alhambra-corral-carbon', 'Transformaciones tras la conquista y subasta de 1531', 'Venta y conversión posterior en corral de comedias.'),
        claim('claim.corral-carbon-fabric-limit', 'geometry',
          'La conservación del edificio nazarí no demuestra por sí sola la organización de sus usos teatrales en 1550.',
          'Survival of the Nasrid building does not by itself establish the arrangement of its theatrical uses in 1550.',
          'source.alhambra-corral-carbon', 'Descripción del edificio y cambios de uso', 'Distingue continuidad de la fábrica y transformación funcional.'),
      ],
      relationships: [relationship('near', 'commerce.alcaiceria',
        'El edificio heredado permanecía en el centro mercantil transformado, próximo a la Alcaicería.',
        'The inherited building remained in the transformed commercial centre near the Alcaicería.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.alhambra-corral-carbon'],
        'No se copia todavía la huella c. 1492: debe comprobarse qué partes y límites representan con honestidad el edificio de 1550.',
        'The 1492 footprint is not copied yet: an audit must establish which parts and edges honestly represent the 1550 building.',
        'Auditar la huella conservada y documentar por separado las adaptaciones teatrales anteriores y posteriores a 1550.',
        'Audit the surviving footprint and separately document theatrical adaptations before and after 1550.'),
    },
    {
      feature_id: 'religious.santa-cruz-real',
      cluster: 'parish_city',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'newly_built', physical_state: 'unknown',
      },
      content: localized(
        'Convento de Santa Cruz la Real',
        'Fundación dominica en las antiguas huertas de la Almanjarra',
        'La fundación de los Reyes Católicos ocupaba hacia 1550 las huertas de la Almanjarra, pero las numerosas reformas del conjunto impiden atribuir al corte una planta acabada.',
        'La fundación y el sitio son seguros; la fuente institucional combina fases góticas, renacentistas y barrocas que deben separarse antes de cartografiar.',
        'El nuevo convento implantó una gran institución cristiana en un paisaje de huertas heredado, sin que pueda asumirse la forma del complejo actual.',
        'Convent of Santa Cruz la Real',
        'Dominican foundation on the former Almanjarra orchards',
        'The Catholic Monarchs’ foundation occupied the Almanjarra orchards around 1550, but the complex’s many alterations prevent attribution of a finished plan to the snapshot.',
        'The foundation and site are secure; the institutional source combines Gothic, Renaissance and Baroque phases that must be separated before mapping.',
        'The new convent inserted a major Christian institution into an inherited orchard landscape, without licensing use of the present complex’s form.',
      ),
      claims: [
        claim('claim.santa-cruz-foundation-site', 'function',
          'Santa Cruz la Real fue fundado por los Reyes Católicos sobre las huertas de la Almanjarra Alta y Baja.',
          'Santa Cruz la Real was founded by the Catholic Monarchs on the Upper and Lower Almanjarra orchards.',
          'source.granada-santa-cruz-real', 'Fundación y emplazamiento', 'Fundación real y ocupación de las huertas de la Almanjarra.'),
        claim('claim.santa-cruz-phase-limit', 'geometry',
          'Las reformas acumuladas del complejo impiden usar su planta actual como geometría de 1550.',
          'Accumulated alterations to the complex prevent use of its present plan as 1550 geometry.',
          'source.granada-santa-cruz-real', 'Descripción de reformas y estilos', 'La mezcla de fases exige una lectura constructiva previa.'),
      ],
      relationships: [relationship('near', 'urban.campo-principe',
        'La fundación participó en la reorganización cristiana del Realejo, pero no define por sí sola los límites del barrio.',
        'The foundation participated in the Christian reorganisation of the Realejo but does not itself define the quarter’s boundaries.')],
      geometry_decision: geometry(
        'create_reference_point_after_site_audit', ['source.granada-santa-cruz-real', 'source.ugr-urban-transformation'],
        'Solo es defendible un punto de sitio tras comprobar el acceso y el núcleo conventual anterior a 1550.',
        'Only a site point is defensible after checking the entrance and conventual core that pre-date 1550.',
        'Fijar una referencia de sitio, identificar fases anteriores a 1550 y mantener aplazada cualquier huella del conjunto.',
        'Fix a site reference, identify pre-1550 phases and keep every complex footprint deferred.'),
    },
    {
      feature_id: 'water.acequia-real-alhambra',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'altered', physical_state: 'complete',
      },
      content: localized(
        'Acequia Real de la Alhambra bajo administración cristiana',
        'Conducción principal de abastecimiento de Generalife y Alhambra',
        'La Acequia Real continuaba haciendo posible el abastecimiento del Generalife y la Alhambra, pero la regulación cristiana y sustituciones del cauce impiden tratarla como una línea inalterada desde 1492.',
        'La continuidad funcional está bien documentada; el trazado conservado es discontinuo y la fase inmediatamente posterior a la conquista necesita una auditoría por tramos.',
        'El sistema heredado permaneció esencial, aunque cambió su gestión y partes de su materialidad después de la conquista.',
        'Royal Canal of the Alhambra under Christian administration',
        'Main water conduit supplying the Generalife and Alhambra',
        'The Royal Canal continued to sustain the Generalife and Alhambra, but Christian regulation and channel replacements prevent treating it as an unchanged line from 1492.',
        'Functional continuity is well documented; the surviving course is discontinuous and the phase immediately after the conquest requires segment-by-segment audit.',
        'The inherited system remained essential, although its management and parts of its material fabric changed after the conquest.',
      ),
      claims: [
        claim('claim.acequia-real-continuity', 'function',
          'La Acequia Real siguió abasteciendo el Generalife, las huertas y la ciudad palatina durante la época cristiana.',
          'The Royal Canal continued to supply the Generalife, its orchards and the palatine city during the Christian period.',
          'source.alhambra-real-acequia-2023', 'Resumen histórico y continuidad de la infraestructura', 'Continuidad prolongada de la conducción después de 1492.'),
        claim('claim.acequia-real-altered', 'transformation',
          'Tras 1492 la conducción fue regulada y algunos sectores del cauce medieval fueron alterados o sustituidos.',
          'After 1492 the conduit was regulated and some stretches of the medieval channel were altered or replaced.',
          'source.alhambra-real-acequia-2023', 'Evolución histórica tras la conquista', 'Alteración del sistema durante la época cristiana.'),
      ],
      relationships: [relationship('routes_toward', 'royal.alhambra',
        'La acequia llevaba agua desde el Darro, atravesaba el Generalife y entraba en la Alhambra para alimentar su red secundaria.',
        'The canal carried water from the Darro through the Generalife and into the Alhambra to feed its secondary network.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.alhambra-real-acequia', 'source.alhambra-real-acequia-2023'],
        'La línea c. 1492 es una hipótesis útil de continuidad, pero no una variante c. 1550 hasta revisar cada tramo alterado.',
        'The 1492 line is a useful continuity hypothesis, but not a 1550 variant until every altered stretch is reviewed.',
        'Clasificar tramos conservados, sustituidos, ocultos y desconocidos y publicar la procedencia de cada segmento.',
        'Classify surviving, replaced, buried and unknown stretches and publish the provenance of each segment.'),
    },
    {
      feature_id: 'religious.san-jeronimo',
      cluster: 'parish_city',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'newly_built', physical_state: 'unknown',
      },
      content: localized(
        'Monasterio de San Jerónimo',
        'Monasterio jerónimo y panteón nobiliario del Gran Capitán',
        'La fundación real estaba presente y el complejo se vinculaba al programa religioso y nobiliario de la Granada cristiana, pero su fase material exacta en 1550 no está resuelta por las fuentes actuales.',
        'La fundación, la iglesia y el monasterio están documentados; se necesita una cronología constructiva especializada para separar el conjunto renacentista visible en 1550.',
        'El monasterio añadió un gran polo religioso extramuros y una memoria dinástica cristiana a la ciudad transformada.',
        'Monastery of San Jerónimo',
        'Hieronymite monastery and noble pantheon of the Great Captain',
        'The royal foundation was present and the complex belonged to Christian Granada’s religious and noble programme, but its exact material phase in 1550 is unresolved by the current sources.',
        'The foundation, church and monastery are documented; a specialist building chronology is needed to separate the Renaissance complex visible in 1550.',
        'The monastery added a major extramural religious centre and a Christian dynastic memorial to the transformed city.',
      ),
      claims: [
        claim('claim.san-jeronimo-royal-foundation', 'function',
          'San Jerónimo fue una fundación de los Reyes Católicos formada por iglesia y monasterio.',
          'San Jerónimo was a foundation of the Catholic Monarchs comprising a church and monastery.',
          'source.granada-san-jeronimo', 'Fundación y composición del conjunto', 'Fundación real y existencia del monasterio y la iglesia.'),
        claim('claim.san-jeronimo-phase-unknown', 'geometry',
          'La descripción general del conjunto no permite delimitar qué fábrica estaba terminada exactamente en 1550.',
          'The general description of the complex does not delimit which fabric was complete precisely in 1550.',
          'source.granada-san-jeronimo', 'Descripción arquitectónica general', 'La fuente no ofrece una planta de fases fechada hacia 1550.'),
      ],
      relationships: [relationship('near', 'gate.elvira',
        'El nuevo polo monástico se situaba fuera del núcleo heredado y se relacionaba con la expansión cristiana más allá de la puerta de Elvira.',
        'The new monastic centre stood outside the inherited core and related to Christian expansion beyond the Elvira gate.')],
      geometry_decision: geometry(
        'create_reference_point_after_site_audit', ['source.granada-san-jeronimo', 'source.ugr-urban-transformation'],
        'Un punto puede identificar el conjunto, pero no debe sugerir una iglesia o claustros plenamente terminados en 1550.',
        'A point may identify the complex but must not imply a fully completed church or cloisters in 1550.',
        'Confirmar el núcleo de obra activo hacia 1550 y registrar por separado iglesia, claustros y dependencias.',
        'Confirm the building core active around 1550 and record church, cloisters and dependencies separately.'),
    },
    {
      feature_id: 'religious.san-jose',
      cluster: 'parish_city',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'replaced', physical_state: 'complete',
      },
      content: localized(
        'Iglesia de San José',
        'Iglesia parroquial mudéjar sobre la mezquita al-Murabitin',
        'La iglesia construida en 1525 reemplazaba la mezquita al-Murabitin y constituía una de las primeras parroquias mudéjares del Albaicín.',
        'La fecha, el solar y la tipología general son seguros; la portada neoclásica y otras fases posteriores deben excluirse de cualquier representación de 1550.',
        'La sustitución cambió institución y fábrica, aunque el registro debe mantener visible el sitio islámico precedente.',
        'Church of San José',
        'Mudéjar parish church on the al-Murabitin mosque site',
        'The church built in 1525 replaced the al-Murabitin mosque and formed one of the earliest Mudéjar parishes in the Albaicín.',
        'The date, site and general type are secure; the Neoclassical portal and other later phases must be excluded from any 1550 representation.',
        'Replacement changed both institution and fabric, although the record must keep the preceding Islamic site visible.',
      ),
      claims: [
        claim('claim.san-jose-built-1525', 'chronology',
          'La iglesia de San José fue construida en 1525 sobre la mezquita al-Murabitin.',
          'The church of San José was built in 1525 on the al-Murabitin mosque.',
          'source.granada-san-jose', 'Cronología y solar', 'Construcción en 1525 sobre la mezquita precedente.'),
        claim('claim.san-jose-later-portal', 'geometry',
          'La portada neoclásica visible hoy no pertenece al estado de 1550.',
          'The Neoclassical portal visible today does not belong to the 1550 state.',
          'source.granada-san-jose', 'Descripción exterior', 'Identificación de una fase neoclásica posterior.'),
      ],
      relationships: [relationship('contained_by', 'urban.albaicin',
        'La nueva parroquia formaba parte de la reorganización cristiana del Albaicín, sin definir por sí sola un límite parroquial.',
        'The new parish belonged to the Christian reorganisation of the Albaicín without itself defining a parish boundary.')],
      geometry_decision: geometry(
        'create_reference_point_after_site_audit', ['source.granada-san-jose'],
        'Se prepara un punto de sitio, no una huella actual que mezcle la iglesia mudéjar y añadidos posteriores.',
        'A site point is prepared, not a present footprint that mixes the Mudéjar church with later additions.',
        'Confirmar el centro del edificio de 1525 y completar una lectura de fases antes de cualquier polígono.',
        'Confirm the centre of the 1525 building and complete a phase reading before any polygon.'),
    },
    {
      feature_id: 'religious.san-juan-reyes',
      cluster: 'parish_city',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'replaced', physical_state: 'complete',
      },
      content: localized(
        'Iglesia de San Juan de los Reyes',
        'Iglesia parroquial mudéjar con alminar islámico conservado',
        'La mezquita consagrada tras la conquista fue demolida en 1520 para levantar una iglesia de tres naves, conservando su alminar como torre adosada.',
        'La secuencia de sustitución y el alminar son seguros; parte del muro actual fue rehecha en el siglo XIX y no pertenece al estado de 1550.',
        'La entidad combina sustitución del templo y continuidad selectiva de una pieza islámica, que debe conservar identidad material propia.',
        'Church of San Juan de los Reyes',
        'Mudéjar parish church with a retained Islamic minaret',
        'The mosque consecrated after the conquest was demolished in 1520 for a three-aisled church, while its minaret survived as an attached tower.',
        'The replacement sequence and minaret are secure; part of the present wall was rebuilt in the nineteenth century and does not belong to the 1550 state.',
        'The entity combines replacement of the temple with selective continuity of an Islamic element that must retain its own material identity.',
      ),
      claims: [
        claim('claim.san-juan-replacement-1520', 'transformation',
          'La mezquita fue demolida en 1520 para levantar la iglesia de San Juan de los Reyes.',
          'The mosque was demolished in 1520 to build the church of San Juan de los Reyes.',
          'source.granada-san-juan-reyes', 'Secuencia de consagración y demolición', 'Demolición de la mezquita y construcción del nuevo templo.'),
        claim('claim.san-juan-minaret-retained', 'transformation',
          'El alminar de la mezquita fue conservado y adosado a la cabecera de la iglesia.',
          'The mosque minaret was retained and attached to the church’s east end.',
          'source.granada-san-juan-reyes', 'Descripción del alminar', 'Conservación material del alminar como elemento del conjunto cristiano.'),
      ],
      relationships: [relationship('contained_by', 'urban.albaicin',
        'La iglesia y el alminar conservado hacen visible la transformación religiosa del Albaicín sin convertirla en un reemplazo material total.',
        'The church and retained minaret make the Albaicín’s religious transformation visible without treating it as total material replacement.')],
      geometry_decision: geometry(
        'create_reference_point_after_site_audit', ['source.granada-san-juan-reyes'],
        'El primer paso será un punto de sitio; cualquier futura huella deberá separar iglesia, alminar retenido y muro rehecho.',
        'The first step will be a site point; any future footprint must separate church, retained minaret and rebuilt wall.',
        'Localizar por separado el alminar y excluir la reconstrucción muraria del siglo XIX mediante una lectura de fábrica.',
        'Locate the minaret separately and exclude the nineteenth-century wall reconstruction through fabric analysis.'),
    },
    {
      feature_id: 'religious.san-matias',
      cluster: 'parish_city',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'replaced', physical_state: 'complete',
      },
      content: localized(
        'Iglesia imperial de San Matías',
        'Iglesia parroquial mudéjar y renacentista trasladada por voluntad imperial',
        'La parroquia se trasladó a su emplazamiento actual por orden de Carlos V y la iglesia, levantada sobre una mezquita, recibió sus capillas laterales entre 1533 y 1541.',
        'La cronología principal precede a 1550; la cubierta de estuco de 1775 y otras transformaciones posteriores no pueden incorporarse al estado histórico.',
        'La ficha se corrige de simple nueva construcción a sustitución, porque la fuente identifica expresamente una mezquita anterior en el solar.',
        'Imperial church of San Matías',
        'Mudéjar and Renaissance parish church relocated by imperial order',
        'The parish moved to its present site by order of Charles V, and the church built over a mosque received its side chapels between 1533 and 1541.',
        'The principal chronology precedes 1550; the 1775 stucco ceiling and other later transformations cannot enter the historical state.',
        'The record is corrected from simple new construction to replacement because the source explicitly identifies an earlier mosque on the site.',
      ),
      claims: [
        claim('claim.san-matias-chapels-1541', 'chronology',
          'Las capillas laterales de San Matías fueron añadidas entre 1533 y 1541.',
          'The side chapels of San Matías were added between 1533 and 1541.',
          'source.granada-san-matias', 'Cronología de las capillas laterales', 'Fase principal documentada antes del corte de 1550.'),
        claim('claim.san-matias-mosque-site', 'transformation',
          'La iglesia fue fundada sobre una mezquita y la parroquia fue trasladada al sitio por orden imperial.',
          'The church was founded over a mosque and the parish was moved to the site by imperial order.',
          'source.granada-san-matias', 'Fundación y traslado', 'Predecesor islámico y traslado de la parroquia al emplazamiento actual.'),
      ],
      relationships: [relationship('near', 'quarter.garnata-al-yahud',
        'La parroquia imperial participó en la reorganización cristiana del área del Realejo próxima al antiguo barrio judío.',
        'The imperial parish participated in the Christian reorganisation of the Realejo area near the former Jewish quarter.')],
      geometry_decision: geometry(
        'create_reference_point_after_site_audit', ['source.granada-san-matias'],
        'Un punto evita copiar la planta actual, cuya cubierta y otros componentes incluyen transformaciones muy posteriores.',
        'A point avoids copying the present plan, whose ceiling and other components include much later transformations.',
        'Confirmar el núcleo de 1533–1541 y separar todas las fases posteriores antes de plantear una huella.',
        'Confirm the 1533–1541 core and separate every later phase before proposing a footprint.'),
    },
    {
      feature_id: 'royal.casa-castril',
      cluster: 'civic_centre',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'unknown', temporal_confidence: 'probable', change_from_1492: 'newly_built', physical_state: 'unknown',
      },
      content: localized(
        'Casa de Castril — cronología c. 1550 no resuelta',
        'Residencia señorial cristiana en la Carrera del Darro',
        'La residencia fue construida en el siglo XVI por un nieto de Hernando de Zafra con autorización de Carlos V, pero la fuente disponible no demuestra qué parte existía exactamente en 1550.',
        'El edificio, promotor y contexto urbano son identificables; se mantiene presencia desconocida hasta obtener fecha documental y lectura de fases suficientes.',
        'La casa representa la implantación residencial de élites cristianas, pero no debe convertirse en un marcador seguro de 1550 solo por pertenecer al siglo XVI.',
        'Casa de Castril — unresolved c. 1550 chronology',
        'Christian elite residence on the Carrera del Darro',
        'The residence was built in the sixteenth century by a grandson of Hernando de Zafra with Charles V’s authorisation, but the available source does not establish what existed precisely in 1550.',
        'The building, patron and urban context are identifiable; presence remains unknown until sufficient documentary dating and phase analysis are available.',
        'The house represents Christian elite residential insertion but must not become a secure 1550 marker merely because it belongs to the sixteenth century.',
      ),
      claims: [
        claim('claim.casa-castril-sixteenth-century', 'chronology',
          'La Casa de Castril es una residencia señorial del siglo XVI construida por un nieto de Hernando de Zafra con autorización imperial.',
          'Casa de Castril is a sixteenth-century elite residence built by a grandson of Hernando de Zafra with imperial authorisation.',
          'source.granada-casa-castril', 'Descripción histórica del museo y edificio', 'Cronología general, promotor y autorización de Carlos V.'),
        claim('claim.casa-castril-1550-unknown', 'interpretation',
          'Una datación general en el siglo XVI no basta para afirmar presencia o terminación en 1550.',
          'A general sixteenth-century date is insufficient to assert presence or completion in 1550.',
          'source.granada-casa-castril', 'Cronología general del edificio', 'La fuente no ofrece una fecha constructiva precisa dentro del siglo XVI.'),
      ],
      relationships: [relationship('near', 'route.darro-axis',
        'La residencia ocupa la Carrera del Darro, pero su fecha incierta impide usarla todavía para reconstruir el frente urbano de 1550.',
        'The residence stands on the Carrera del Darro, but its uncertain date prevents using it to reconstruct the 1550 street frontage.')],
      geometry_decision: geometry(
        'no_geometry_until_chronology_resolved', ['source.granada-casa-castril'],
        'Ni siquiera un punto c. 1550 debe publicarse mientras la presencia en la ventana 1540–1560 siga sin demostrarse.',
        'Not even a 1550 point should be published while presence within the 1540–1560 window remains unproven.',
        'Obtener una fecha constructiva documentada y una lectura de fases que identifique la fábrica anterior a 1560.',
        'Obtain documented construction dating and phase analysis identifying fabric earlier than 1560.'),
    },
    {
      feature_id: 'royal.casa-tiros',
      cluster: 'civic_centre',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'unknown', temporal_confidence: 'probable', change_from_1492: 'newly_built', physical_state: 'unknown',
      },
      content: localized(
        'Casa de los Tiros — cronología c. 1550 no resuelta',
        'Residencia señorial fortificada del Realejo',
        'La Casa de los Tiros es un edificio residencial renacentista del siglo XVI, pero la fuente institucional disponible no permite afirmar su presencia o estado material exacto en 1550.',
        'El sitio, la función residencial y la cronología amplia son seguros; faltan fecha de obra y análisis de fases para el intervalo 1540–1560.',
        'La residencia puede contextualizar la nueva arquitectura nobiliaria, pero no debe aparecer todavía como objeto cartográfico de 1550.',
        'Casa de los Tiros — unresolved c. 1550 chronology',
        'Fortified elite residence in the Realejo',
        'Casa de los Tiros is a sixteenth-century Renaissance residence, but the available institutional source cannot establish its presence or exact material state in 1550.',
        'The site, residential function and broad chronology are secure; construction dating and phase analysis for 1540–1560 are missing.',
        'The residence can contextualise new elite architecture but must not yet appear as a mapped 1550 object.',
      ),
      claims: [
        claim('claim.casa-tiros-sixteenth-century', 'chronology',
          'La Casa de los Tiros es un edificio renacentista del siglo XVI situado en el Realejo.',
          'Casa de los Tiros is a sixteenth-century Renaissance building in the Realejo.',
          'source.granada-casa-tiros', 'Descripción y localización', 'Cronología general del siglo XVI y ubicación en el Realejo.'),
        claim('claim.casa-tiros-1550-unknown', 'interpretation',
          'La cronología amplia no permite asignar a 1550 la fachada ni la organización conservada del edificio.',
          'The broad chronology does not allow the surviving façade or organisation to be assigned to 1550.',
          'source.granada-casa-tiros', 'Descripción institucional del edificio', 'Ausencia de una fecha y secuencia constructiva precisas.'),
      ],
      relationships: [relationship('contained_by', 'quarter.garnata-al-yahud',
        'La casa se integra en el Realejo transformado, pero no prueba por sí sola la cronología ni los límites del antiguo barrio.',
        'The house belongs to the transformed Realejo but does not itself establish the chronology or boundaries of the former quarter.')],
      geometry_decision: geometry(
        'no_geometry_until_chronology_resolved', ['source.granada-casa-tiros'],
        'Se excluye del mapa candidato hasta que una fuente determine presencia y fase dentro de la ventana documental.',
        'It remains outside the candidate map until evidence establishes presence and phase within the documentary window.',
        'Conseguir datación de obra y lectura de fábrica suficiente para separar elementos anteriores y posteriores a 1550.',
        'Obtain construction dating and fabric analysis sufficient to separate pre- and post-1550 elements.'),
    },
    {
      feature_id: 'religious.san-luis',
      cluster: 'parish_city',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'replaced', physical_state: 'complete',
      },
      content: localized(
        'Iglesia de San Luis',
        'Iglesia parroquial mudéjar sobre la mezquita de la Pureza',
        'La iglesia de cajón terminada en 1526 ocupaba el solar de la mezquita de la Pureza y era una presencia parroquial segura en el Albaicín de 1550.',
        'La fecha y la tipología original están documentadas; incendios, ruina y restauraciones posteriores obligan a no copiar automáticamente la geometría actual.',
        'El nuevo templo reemplazó la mezquita en el mismo solar, combinando ruptura institucional y continuidad del lugar religioso.',
        'Church of San Luis',
        'Mudéjar parish church on the Mosque of Purity site',
        'The box-plan church completed in 1526 occupied the Mosque of Purity site and was a secure parish presence in the Albaicín of 1550.',
        'Its date and original type are documented; later fire, ruin and restoration mean the present geometry cannot be copied automatically.',
        'The new church replaced the mosque on the same site, combining institutional rupture with continuity of the religious place.',
      ),
      claims: [
        claim('claim.san-luis-complete-1526', 'chronology',
          'La construcción de San Luis finalizó en 1526 siguiendo una tipología mudéjar de iglesia de cajón.',
          'Construction of San Luis was completed in 1526 using a Mudéjar box-church type.',
          'source.granada-san-luis', 'Ficha Iglesia de San Luis', 'Finalización en 1526 y tipología arquitectónica original.'),
        claim('claim.san-luis-mosque-site', 'transformation',
          'San Luis se levantó sobre el solar de la mezquita de la Pureza, Masŷd al-Ṣafā.',
          'San Luis was built on the site of the Mosque of Purity, Masjid al-Safa.',
          'source.granada-san-luis', 'Ficha Iglesia de San Luis', 'Identificación del solar de la mezquita precedente.'),
      ],
      relationships: [relationship('contained_by', 'urban.albaicin',
        'La iglesia formaba parte del nuevo sistema parroquial del Albaicín, aunque su posición no define una jurisdicción territorial.',
        'The church belonged to the Albaicín’s new parish system, although its position does not define a territorial jurisdiction.')],
      geometry_decision: geometry(
        'create_reference_point_after_site_audit', ['source.granada-san-luis'],
        'Se propone un punto de sitio porque la geometría visible incorpora pérdida y reconstrucción posteriores al siglo XVI.',
        'A site point is proposed because the visible geometry incorporates loss and reconstruction after the sixteenth century.',
        'Confirmar el solar y documentar la planta original de 1526 antes de crear cualquier huella histórica.',
        'Confirm the site and document the original 1526 plan before creating any historical footprint.'),
    },
  ],
})

await writeFile(outputPath, `${JSON.stringify(tranche, null, 2)}\n`, 'utf8')
console.log(`Tramo de fuentes M10.5 preparado: ${tranche.items.length} fichas bilingües; cero geometrías nuevas.`)

function localized(
  esName: string, esFunction: string, esSummary: string, esEvidence: string, esChange: string,
  enName: string, enFunction: string, enSummary: string, enEvidence: string, enChange: string,
) {
  return {
    es: { name: esName, function: esFunction, summary: esSummary, evidence_note: esEvidence, change_note: esChange },
    en: { name: enName, function: enFunction, summary: enSummary, evidence_note: enEvidence, change_note: enChange },
  }
}

function claim(
  claimId: string,
  topic: 'chronology' | 'function' | 'transformation' | 'geometry' | 'interpretation',
  es: string,
  en: string,
  sourceId: string,
  locator: string,
  supports: string,
) {
  return {
    claim_id: claimId,
    topic,
    text: { es, en },
    citations: [{ source_id: sourceId, locator, supports }],
  }
}

function relationship(
  relation: 'adjacent_to' | 'attached_to' | 'contained_by' | 'near' | 'overlaps' | 'part_of_program_with' | 'replaces_function_of' | 'retains' | 'routes_toward' | 'shares_site_with' | 'transformed_from',
  targetId: string,
  es: string,
  en: string,
) {
  return { relation, target_id: targetId, note: { es, en } }
}

function geometry(
  action: 'retain_existing_only_after_audit' | 'create_reference_point_after_site_audit' | 'no_geometry_until_chronology_resolved',
  sourceRefs: string[],
  rationaleEs: string,
  rationaleEn: string,
  conditionEs: string,
  conditionEn: string,
) {
  return {
    status: 'deferred' as const,
    action,
    rationale: { es: rationaleEs, en: rationaleEn },
    release_condition: { es: conditionEs, en: conditionEn },
    source_refs: sourceRefs,
  }
}
