import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  c1550M10_5SourceReview4Schema,
  M10_5_SOURCE_REVIEW_4_FEATURE_IDS,
} from '../src/data/temporalSchema'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = resolve(repositoryRoot, 'data/research/c1550/m10.5-source-review-4.json')

const tranche = c1550M10_5SourceReview4Schema.parse({
  schema_version: 1,
  milestone: 'M10.5',
  tranche: 'source-review-4',
  period_id: 'c1550',
  status: 'ready_for_content_review',
  public_application_import: false,
  updated_on: '2026-10-02',
  scope_note: 'Cuarto tramo de diez puertas, cercas interiores, acequias y rutas heredadas preparado para revisión histórica sin crear geometría c. 1550.',
  feature_ids: M10_5_SOURCE_REVIEW_4_FEATURE_IDS,
  items: [
    {
      feature_id: 'gate.alfajjarin',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'probable', change_from_1492: 'altered', physical_state: 'partially_in_use',
      },
      content: localized(
        'Puerta de los Alfareros',
        'Paso interior entre la ciudad baja y el Realejo',
        'Hacia 1550 la antigua Bab al-Fajjarin probablemente seguía organizando el paso por Plaza Fortuny, aunque el entorno artesanal y residencial había sido reordenado bajo instituciones cristianas.',
        'La cerca y el ámbito de la puerta están bien localizados, y la Casa de los Girones ofrece un control contextual de 1554; ninguna de esas evidencias demuestra por sí sola la forma o apertura exacta del vano en 1550.',
        'La puerta dejó de ser un acceso hacia un arrabal exterior y pasó a funcionar, si continuaba abierta, como umbral interior de un barrio integrado y transformado.',
        'Potters’ Gate',
        'Internal passage between the lower city and Realejo',
        'Around 1550 the former Bab al-Fajjarin probably continued to organise passage through Plaza Fortuny, although its artisanal and residential surroundings had been reordered under Christian institutions.',
        'The wall and gate area are well located, and the Casa de los Girones provides a contextual control from 1554; neither body of evidence by itself establishes the exact form or openness of the passage in 1550.',
        'The gate ceased to be an entrance to an outer suburb and, if still open, functioned as an internal threshold within an integrated and transformed district.',
      ),
      claims: [
        claim('claim.alfajjarin-gate-wall-context', 'geometry',
          'La puerta de los Alfareros se abría en la cerca que descendía desde Torres Bermejas y separaba el Mauror del Realejo.',
          'The Potters’ Gate opened in the wall descending from Torres Bermejas and separating Mauror from Realejo.',
          'source.junta-aguado-2009', 'Contexto histórico-arqueológico, cerca interior y puertas', 'Fija el sistema defensivo y el ámbito de la puerta sin ofrecer una planta de 1550.'),
        claim('claim.alfajjarin-girones-1554-context', 'transformation',
          'La cercana Casa de los Girones, junto a la muralla y próxima a Bab al-Fajjarin, cambió de propiedad en 1554 después de haber pertenecido a la Inquisición.',
          'The nearby Casa de los Girones, beside the wall and close to Bab al-Fajjarin, changed ownership in 1554 after having belonged to the Inquisition.',
          'source.alhambra-casa-girones-2018', 'Historia de la casa y adquisición de 1554', 'Aporta un control fechado de transformación del entorno, no una atestación directa del vano.'),
      ],
      relationships: [
        relationship('attached_to', 'walls.mauror-realejo-inner',
          'La puerta pertenecía a la cerca interior del Mauror y el Realejo.',
          'The gate belonged to the inner wall of Mauror and Realejo.'),
        relationship('near', 'religious.santa-cruz-real',
          'El convento dominico transformó el entorno de Santo Domingo y Plaza Fortuny.',
          'The Dominican convent transformed the Santo Domingo and Plaza Fortuny area.'),
      ],
      geometry_decision: geometry(
        'no_geometry_until_chronology_resolved',
        ['source.junta-aguado-2009', 'source.junta-cuesta-pescado-2023', 'source.alhambra-casa-girones-2018'],
        'El punto c. 1492 representa el ámbito historiográfico de Plaza Fortuny, no un umbral excavado ni una prueba de que el vano permaneciera abierto en 1550.',
        'The c. 1492 point represents the historiographical Plaza Fortuny area, not an excavated threshold or proof that the passage remained open in 1550.',
        'Localizar una atestación documental o estratigráfica de la puerta en el siglo XVI y separar puerta, cerca y reordenación conventual.',
        'Locate documentary or stratigraphic evidence for the gate in the sixteenth century and separate gate, wall and convent-related reordering.'),
    },
    {
      feature_id: 'gate.guadix',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'probable', change_from_1492: 'retained', physical_state: 'unknown',
      },
      content: localized(
        'Puerta de Guadix',
        'Acceso oriental del Albaicín hacia el valle del Darro',
        'La Puerta de Guadix probablemente continuaba hacia 1550 como salida oriental del Albaicín, conectando el final del corredor del Darro con los caminos exteriores.',
        'La pertenencia al sistema amurallado y la localización general son sólidas, pero no se ha identificado una atestación puntual que describa el vano, su nombre o su estado material dentro de la ventana 1540–1560.',
        'El acceso heredado conservó probablemente su función viaria mientras el borde oriental del Albaicín y el corredor del Darro cambiaban de uso y jerarquía.',
        'Guadix Gate',
        'Eastern Albaicín entrance toward the Darro valley',
        'The Guadix Gate probably continued around 1550 as the eastern exit from the Albaicín, linking the end of the Darro corridor with outward routes.',
        'Its place in the wall system and general location are well established, but no specific attestation has been identified describing the passage, its name or its material condition within the 1540–1560 window.',
        'The inherited entrance probably retained its route function while the eastern edge of the Albaicín and the Darro corridor changed in use and hierarchy.',
      ),
      claims: [
        claim('claim.guadix-gate-eastern-location', 'function',
          'La puerta se situaba al final del actual Paseo de los Tristes y enlazaba la cerca nazarí del Albaicín con el corredor oriental.',
          'The gate stood at the end of today’s Paseo de los Tristes and linked the Nasrid Albaicín wall with the eastern corridor.',
          'source.granada-albaicin-wall-route', 'Recorrido de la muralla del Albayzín', 'Establece localización y relación funcional, pero no una planta del vano.'),
        claim('claim.guadix-gate-period-limit', 'interpretation',
          'La iconografía tardía del siglo XVI permite contrastar la legibilidad general del borde urbano, pero no convierte una vista panorámica en prueba directa del estado de la puerta en 1550.',
          'Late-sixteenth-century iconography can test the general legibility of the urban edge but does not turn a panoramic view into direct evidence for the gate’s condition in 1550.',
          'source.ugr-vico-2023', 'Análisis urbano e iconográfico de la Plataforma de Vico', 'Define el valor y los límites de la fuente visual cercana al periodo.'),
      ],
      relationships: [
        relationship('attached_to', 'walls.albaicin-north',
          'La puerta marcaba el extremo oriental del recinto ampliado del Albaicín.',
          'The gate marked the eastern end of the enlarged Albaicín enclosure.'),
        relationship('near', 'water.darro',
          'El acceso se situaba junto al corredor del Darro y sus caminos de ribera.',
          'The entrance stood beside the Darro corridor and its riverside routes.'),
      ],
      geometry_decision: geometry(
        'no_geometry_until_chronology_resolved',
        ['source.granada-albaicin-wall-route', 'source.ugr-vico-2023'],
        'El punto heredado localiza un cruce moderno de referencia y no una puerta excavada o representada con precisión métrica.',
        'The inherited point locates a modern reference junction, not an excavated gate or a metrically precise depiction.',
        'Encontrar documentación del acceso durante el siglo XVI o evidencia arqueológica del umbral antes de crear una variante c. 1550.',
        'Find sixteenth-century documentation of the entrance or archaeological evidence of the threshold before creating a c. 1550 variant.'),
    },
    {
      feature_id: 'gate.molinos',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'retained', physical_state: 'complete',
      },
      content: localized(
        'Puerta de los Molinos',
        'Salida meridional hacia los molinos del Genil y los caminos de la sierra',
        'Hacia 1550 la antigua Puerta de la Loma seguía en pie y era conocida por su relación con los molinos y el camino de Güéjar, manteniendo la salida meridional desde el Realejo alto.',
        'La continuidad hasta su demolición en 1833 sostiene su presencia, pero las reconstrucciones discrepan en la posición métrica y no ofrecen una planta segura del recodo en 1550.',
        'El acceso nazarí fue retenido con denominaciones cristianas ligadas a los usos productivos y territoriales que articulaba.',
        'Mills Gate',
        'Southern exit toward the Genil mills and mountain routes',
        'Around 1550 the former Gate of the Hill remained standing and was known through its connection with the mills and the road to Güéjar, maintaining the southern exit from upper Realejo.',
        'Its survival until demolition in 1833 supports its presence, but reconstructions disagree on the metric position and provide no secure plan of the bent entrance in 1550.',
        'The Nasrid entrance was retained under Christian names tied to the productive and territorial uses it served.',
      ),
      claims: [
        claim('claim.molinos-gate-survival', 'chronology',
          'La Puerta de la Loma, conocida después como Puerta de los Molinos o de Güéjar, sobrevivió hasta su demolición definitiva en 1833.',
          'The Gate of the Hill, later known as the Mills or Güéjar Gate, survived until its final demolition in 1833.',
          'source.junta-hoteles-belen-2020', 'Contexto histórico-arqueológico general', 'La fecha de demolición asegura que la puerta existía en 1550.'),
        claim('claim.molinos-gate-southern-route', 'function',
          'La puerta se integraba en la cerca sur y comunicaba La Loma con el Genil, los molinos y los caminos meridionales.',
          'The gate formed part of the southern wall and linked La Loma with the Genil, the mills and southern routes.',
          'source.junta-aguado-2009', 'Descripción de la cerca sur, Puerta de la Loma y Cuesta de los Molinos', 'Sostiene la función territorial sin fijar el eje exterior completo.'),
      ],
      relationships: [
        relationship('near', 'urban.campo-principe',
          'La puerta se situaba al sureste del espacio que se consolidó como Campo del Príncipe.',
          'The gate stood southeast of the space consolidated as Campo del Príncipe.'),
        relationship('routes_toward', 'route.molinos-sierra-axis',
          'El acceso daba paso al corredor de los molinos y la sierra.',
          'The entrance opened onto the mills and mountain corridor.'),
      ],
      geometry_decision: geometry(
        'retain_existing_only_after_audit',
        ['source.junta-hoteles-belen-2020', 'source.junta-aguado-2009'],
        'El punto c. 1492 aproxima una confluencia viaria moderna y no distingue la puerta, el recodo ni los lienzos adyacentes.',
        'The c. 1492 point approximates a modern road junction and does not distinguish the gate, bent passage or adjacent wall sections.',
        'Contrastar planos anteriores a 1833, parcelario y evidencia de subsuelo antes de reutilizar el punto para 1550.',
        'Compare pre-1833 plans, parcels and subsurface evidence before reusing the point for 1550.'),
    },
    {
      feature_id: 'gate.pescado',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'retained', physical_state: 'complete',
      },
      content: localized(
        'Puerta del Pescado',
        'Acceso meridional del Realejo hacia el Genil y los caminos de la costa',
        'La Puerta del Pescado seguía activa hacia 1550 como acceso exterior de los barrios meridionales y recibió su nombre cristiano por el tránsito de pescado procedente de la costa.',
        'La continuidad material posterior sostiene su presencia, pero el punto actual solo aproxima el ámbito y no representa los tres arcos ni el pasadizo documentados antes de su demolición.',
        'El acceso nazarí fue retenido y renombrado según un flujo comercial cristiano, sin que ello implique que su fábrica permaneciera inalterada.',
        'Fish Gate',
        'Southern Realejo entrance toward the Genil and coastal routes',
        'The Fish Gate remained active around 1550 as an outer entrance to the southern districts and received its Christian name from fish traffic arriving from the coast.',
        'Later material continuity supports its presence, but the present point only approximates the area and does not represent the three arches and passage documented before demolition.',
        'The Nasrid entrance was retained and renamed after a Christian commercial flow, without implying that its fabric remained unchanged.',
      ),
      claims: [
        claim('claim.pescado-gate-southern-enclosure', 'function',
          'La puerta formaba parte de la cerca exterior que protegía los arrabales de los Alfareros y la Antequeruela y comunicaba con los caminos meridionales.',
          'The gate formed part of the outer wall protecting the Potters’ suburb and Antequeruela and communicated with southern routes.',
          'source.junta-cuesta-pescado-2023', 'Contexto histórico de los arrabales meridionales', 'Establece el sistema, el ámbito y la función del acceso.'),
        claim('claim.pescado-gate-christian-name', 'transformation',
          'La denominación Puerta del Pescado se vinculó al paso de vendedores que entraban desde la costa, mostrando una resignificación cristiana del acceso heredado.',
          'The name Fish Gate was linked to vendors entering from the coast, showing a Christian re-signification of the inherited entrance.',
          'source.junta-aguado-2009', 'Contexto histórico y toponimia de las puertas meridionales', 'Sostiene la continuidad funcional y el cambio de nombre.'),
      ],
      relationships: [
        relationship('near', 'religious.santa-cruz-real',
          'El acceso se situaba en el corredor meridional próximo al Cuarto Real de Santo Domingo.',
          'The entrance stood in the southern corridor near the Cuarto Real de Santo Domingo.'),
      ],
      geometry_decision: geometry(
        'retain_existing_only_after_audit',
        ['source.junta-cuesta-pescado-2023', 'source.junta-aguado-2009'],
        'El punto heredado expresa un emplazamiento aproximado junto a la cuesta homónima, no la huella arquitectónica del acceso.',
        'The inherited point expresses an approximate location beside the namesake slope, not the architectural footprint of the entrance.',
        'Cruzar cartografía anterior a la demolición, descripción arquitectónica y controles arqueológicos antes de fijar la variante c. 1550.',
        'Cross-reference pre-demolition mapping, architectural description and archaeological controls before fixing the c. 1550 variant.'),
    },
    {
      feature_id: 'walls.alcazaba-qadima-inner',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'altered', physical_state: 'partially_in_use',
      },
      content: localized(
        'Cerca interior de la Alcazaba Qadima',
        'Recinto zirí heredado, integrado parcialmente en el caserío del Albaicín',
        'Hacia 1550 la cerca de la Alcazaba Qadima persistía mediante puertas, torres y lienzos incorporados al tejido doméstico y parroquial, ya sin funcionar como un circuito defensivo íntegro.',
        'La arqueología demuestra conservación y reutilización en puntos concretos; la línea completa combina tramos de distinta fecha, supervivencia y precisión y no puede trasladarse uniformemente al corte de 1550.',
        'El antiguo recinto interior perdió unidad militar y fue absorbido por edificios y parcelas, aunque siguió condicionando recorridos y límites locales.',
        'Inner wall of the Alcazaba Qadima',
        'Inherited Zirid enclosure partly incorporated into the Albaicín building fabric',
        'Around 1550 the Alcazaba Qadima wall persisted through gates, towers and sections incorporated into domestic and parish fabric, no longer operating as a complete defensive circuit.',
        'Archaeology demonstrates survival and reuse at specific points; the complete line combines sections of different dates, survival and precision and cannot be transferred uniformly to the 1550 slice.',
        'The former inner enclosure lost military unity and was absorbed by buildings and parcels while continuing to condition local routes and boundaries.',
      ),
      claims: [
        claim('claim.qadima-wall-reused-in-buildings', 'transformation',
          'En la Placeta de las Escuelas se documentaron un lienzo y un torreón zirí reutilizados por edificaciones posteriores.',
          'At Placeta de las Escuelas a Zirid wall section and tower were documented as reused by later buildings.',
          'source.junta-placeta-escuelas-2011', 'Resultados arqueológicos y análisis de estructuras emergentes', 'Prueba supervivencia material localizada y absorción en el caserío.'),
        claim('claim.qadima-wall-monaita-segment', 'geometry',
          'La investigación en torno a Puerta Monaita documenta fábrica conservada y relaciones estratigráficas del recinto de la Alcazaba Qadima.',
          'Research around Monaita Gate documents surviving fabric and stratigraphic relationships in the Alcazaba Qadima enclosure.',
          'source.junta-monaita-wall-2000', 'Estudio histórico y resultados arqueológicos', 'Aporta controles físicos parciales, no una fecha uniforme para todo el circuito.'),
      ],
      relationships: [
        relationship('attached_to', 'gate.monaita',
          'Puerta Monaita era uno de los principales accesos conservados del recinto.',
          'Monaita Gate was one of the enclosure’s principal surviving entrances.'),
        relationship('contained_by', 'urban.albaicin',
          'La antigua cerca había quedado integrada dentro del conjunto urbano del Albaicín.',
          'The former wall had become integrated within the Albaicín urban fabric.'),
      ],
      geometry_decision: geometry(
        'retain_existing_only_after_audit',
        ['source.junta-monaita-wall-2000', 'source.junta-placeta-escuelas-2011', 'source.granada-pepri-islamic-city'],
        'La línea c. 1492 presenta una hipótesis continua aunque la evidencia de 1550 corresponde a restos, reutilizaciones y desapariciones desiguales.',
        'The c. 1492 line presents a continuous hypothesis although the 1550 evidence consists of uneven remains, reuse and loss.',
        'Dividir el circuito en segmentos con estado material, cronología, evidencia y tolerancia propios antes de crear una línea temporal.',
        'Divide the circuit into segments with their own material state, chronology, evidence and tolerance before creating a temporal line.'),
    },
    {
      feature_id: 'walls.axares-inner',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'probable', change_from_1492: 'altered', physical_state: 'partially_in_use',
      },
      content: localized(
        'Cerca interior de Axares',
        'Límite heredado del barrio de Axares dentro del Albaicín',
        'La cerca de Axares probablemente seguía siendo legible de forma fragmentaria hacia 1550, absorbida por el caserío y subordinada al recinto exterior del Albaicín.',
        'Las fuentes permiten reconstruir el barrio y algunos contactos, pero no demuestran que todo el circuito interpretativo permaneciera en pie ni conservase función defensiva en el periodo.',
        'El antiguo límite barrial pasó de defensa urbana a condicionante parcelario y topográfico, con pérdidas y reutilizaciones desiguales.',
        'Inner wall of Axares',
        'Inherited boundary of the Axares district within the Albaicín',
        'The Axares wall probably remained fragmentarily legible around 1550, absorbed by the building fabric and subordinate to the outer Albaicín enclosure.',
        'Sources allow reconstruction of the district and some contacts but do not show that the entire interpreted circuit remained standing or retained a defensive function in the period.',
        'The former district boundary shifted from urban defence to a parcel and topographic constraint, with uneven loss and reuse.',
      ),
      claims: [
        claim('claim.axares-wall-medieval-enclosure', 'chronology',
          'El barrio de Axares quedó cercado entre la Alcazaba Qadima, la Cuesta del Chapiz, el Darro y la coracha antes de la gran ampliación nazarí.',
          'The Axares district was enclosed between the Alcazaba Qadima, Cuesta del Chapiz, the Darro and the coracha before the major Nasrid expansion.',
          'source.junta-carmen-negro-2005', 'Contexto urbano medieval', 'Establece el sistema heredado cuya supervivencia debe evaluarse por tramos.'),
        claim('claim.axares-wall-sixteenth-century-limit', 'interpretation',
          'La reconstrucción urbana permite reconocer la cerca como límite interior, pero no asignar continuidad material homogénea a todos sus lados en 1550.',
          'Urban reconstruction allows the wall to be recognised as an inner boundary but does not assign homogeneous material continuity to every side in 1550.',
          'source.granada-pepri-islamic-city', 'Memoria urbana, evolución del recinto islámico', 'Sostiene la lectura territorial y obliga a separar hipótesis de fábrica conservada.'),
      ],
      relationships: [
        relationship('near', 'walls.alcazaba-qadima-inner',
          'La cerca de Axares se adosaba y relacionaba con el recinto anterior de la Alcazaba Qadima.',
          'The Axares wall adjoined and related to the earlier Alcazaba Qadima enclosure.'),
        relationship('near', 'water.darro',
          'El frente meridional del barrio se organizaba sobre el corredor del Darro.',
          'The district’s southern front was organised along the Darro corridor.'),
      ],
      geometry_decision: geometry(
        'no_geometry_until_chronology_resolved',
        ['source.junta-carmen-negro-2005', 'source.granada-pepri-islamic-city', 'source.ujaen-water-route-2025'],
        'La línea heredada cierra una envolvente territorial interpretativa y usa referencias modernas donde no existe fábrica continua comprobada.',
        'The inherited line closes an interpretative territorial envelope and uses modern references where no continuous verified fabric survives.',
        'Inventariar por segmentos la evidencia arqueológica y la absorción parcelaria antes de dibujar un estado c. 1550.',
        'Inventory archaeological evidence and parcel absorption by segment before drawing a c. 1550 state.'),
    },
    {
      feature_id: 'walls.mauror-realejo-inner',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'probable', change_from_1492: 'altered', physical_state: 'partially_in_use',
      },
      content: localized(
        'Cerca interior del Mauror y el Realejo',
        'Límite urbano heredado entre la ciudad anterior, el Mauror y los arrabales meridionales',
        'Hacia 1550 la cerca interior entre Torres Bermejas, Alfareros y Santo Domingo persistía probablemente en fragmentos, incorporada a parcelas y edificios de un Realejo ya integrado.',
        'La arqueología y la topografía sostienen el corredor general, pero no una línea continua ni un estado material uniforme dentro de la ventana documental.',
        'La cerca perdió su función como borde total de la ciudad y quedó convertida en límite interior, soporte edificatorio y condicionante del viario.',
        'Inner wall of Mauror and Realejo',
        'Inherited urban boundary between the earlier city, Mauror and the southern suburbs',
        'Around 1550 the inner wall between Torres Bermejas, the Potters’ Gate and Santo Domingo probably persisted in fragments, incorporated into parcels and buildings of an integrated Realejo.',
        'Archaeology and topography support the general corridor but not a continuous line or uniform material state within the documentary window.',
        'The wall lost its role as the city’s overall edge and became an inner boundary, building support and constraint on the street network.',
      ),
      claims: [
        claim('claim.mauror-inner-wall-course', 'geometry',
          'La cerca descendía desde Torres Bermejas hacia el Cuarto Real y abría pasos como Bab al-Fajjarin y Bab Mauror.',
          'The wall descended from Torres Bermejas toward the Cuarto Real and opened passages including Bab al-Fajjarin and Bab Mauror.',
          'source.junta-aguado-2009', 'Contexto histórico-arqueológico de la cerca interior', 'Define el corredor histórico sin fijar cada tramo para 1550.'),
        claim('claim.mauror-inner-wall-urban-integration', 'transformation',
          'La ampliación exterior nazarí dejó esta cerca dentro del recinto urbano, donde la transformación posterior favoreció su absorción y fragmentación.',
          'The later Nasrid outer expansion left this wall within the urban enclosure, where subsequent transformation encouraged absorption and fragmentation.',
          'source.garrido-alfareros-2024', 'pp. 663–679, configuración del arrabal y sus cercas', 'Explica el cambio de jerarquía del límite y la evolución del entorno artesanal.'),
      ],
      relationships: [
        relationship('attached_to', 'gate.alfajjarin',
          'Bab al-Fajjarin articulaba uno de los pasos principales de la cerca.',
          'Bab al-Fajjarin organised one of the wall’s principal passages.'),
        relationship('attached_to', 'gate.mawrur',
          'Bab Mauror conectaba el sector alto con el barrio interior.',
          'Bab Mauror linked the upper sector with the inner district.'),
      ],
      geometry_decision: geometry(
        'retain_existing_only_after_audit',
        ['source.junta-aguado-2009', 'source.junta-porteria-santo-domingo-2012', 'source.garrido-alfareros-2024'],
        'La línea pública es una síntesis del corredor y no distingue restos comprobados, tramos absorbidos y enlaces hipotéticos.',
        'The public line is a corridor synthesis and does not distinguish verified remains, absorbed sections and hypothetical links.',
        'Clasificar cada segmento por supervivencia y fuente, y resolver la cronología de los contactos con Santo Domingo y Torres Bermejas.',
        'Classify every segment by survival and source, and resolve the chronology of the contacts with Santo Domingo and Torres Bermejas.'),
    },
    {
      feature_id: 'water.acequia-axares',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'retained', physical_state: 'complete',
      },
      content: localized(
        'Acequia de Axares o de San Juan',
        'Canal derivado del Darro para abastecimiento urbano del Albaicín y la ciudad baja',
        'La Acequia de Axares, llamada también de San Juan, estaba activa y regulada en 1538, con ramales que abastecían el corredor de San Juan de los Reyes y destinos urbanos heredados.',
        'Las ordenanzas aseguran operación, limpieza y destinos, pero no proporcionan un levantamiento métrico continuo ni prueban que todas las acometidas medievales siguieran iguales en 1550.',
        'La infraestructura continuó bajo administración cristiana y una nueva toponimia, mientras cambiaban instituciones receptoras y ramales locales.',
        'Axares or San Juan Canal',
        'Darro-derived canal supplying the Albaicín and lower city',
        'The Axares Canal, also called San Juan, was active and regulated in 1538, with branches supplying the San Juan de los Reyes corridor and inherited urban destinations.',
        'The ordinances establish operation, cleaning and destinations but provide no continuous metric survey and do not show that every medieval service branch remained unchanged in 1550.',
        'The infrastructure continued under Christian administration and new naming while recipient institutions and local branches changed.',
      ),
      claims: [
        claim('claim.axares-canal-ordinances-1538', 'chronology',
          'Las ordenanzas de 1538 regulaban la limpieza y vigilancia de la Acequia de Axares, identificada también con San Juan.',
          'The 1538 ordinances regulated cleaning and inspection of the Axares Canal, also identified with San Juan.',
          'source.ugr-water-ordinances-2022', 'Apartado sobre Romayla, Axares y Darrillo', 'Atestigua directamente el funcionamiento del canal próximo al periodo.'),
        claim('claim.axares-canal-urban-destinations', 'function',
          'La red de Axares abastecía el corredor de San Juan y se relacionaba con depósitos y edificios de la ciudad baja.',
          'The Axares network supplied the San Juan corridor and related to reservoirs and buildings in the lower city.',
          'source.ujaen-water-route-2025', 'Mapa 5 y discusión de la Acequia de Axares/San Juan', 'Sostiene el corredor y los destinos generales sin fijar cada ramal.'),
      ],
      relationships: [
        relationship('retains', 'water.darro',
          'La acequia derivaba del sistema del Darro.',
          'The canal derived from the Darro system.'),
        relationship('routes_toward', 'religious.medina-great-mosque',
          'La red heredada alcanzaba el centro urbano y su gran aljibe, aunque las acometidas cambiaron tras la conversión.',
          'The inherited network reached the urban centre and its great cistern, although service branches changed after conversion.'),
      ],
      geometry_decision: geometry(
        'retain_existing_only_after_audit',
        ['source.ugr-water-ordinances-2022', 'source.ujaen-water-route-2025', 'source.granada-pepri-islamic-city'],
        'La línea c. 1492 generaliza el cauce principal y una llegada al centro sin separar ramales, tramos cubiertos y acometidas alteradas.',
        'The c. 1492 line generalises the main channel and an approach to the centre without separating branches, covered sections and altered service connections.',
        'Convertir las descripciones de 1538 en controles por segmento y documentar cada bifurcación antes de crear la línea c. 1550.',
        'Turn the 1538 descriptions into segment controls and document each bifurcation before creating the c. 1550 line.'),
    },
    {
      feature_id: 'water.acequia-realejo',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'altered', physical_state: 'complete',
      },
      content: localized(
        'Ramal del Realejo',
        'Ramal de la Acequia Gorda para abastecimiento, riego y fuerza motriz',
        'El ramal del Realejo estaba activo en la primera mitad del siglo XVI, abastecía el barrio y contribuía a mover molinos antes de devolver o distribuir el agua hacia la Vega.',
        'La regulación hidráulica demuestra continuidad funcional, pero el ramal reconstruido combina cauce principal, repartidores y salidas cuya posición y fase deben verificarse separadamente.',
        'La red medieval continuó bajo regulación cristiana y se adaptó a conventos, residencias, espacios públicos y usos productivos nuevos o reorganizados.',
        'Realejo branch',
        'Branch of the Acequia Gorda for supply, irrigation and motive power',
        'The Realejo branch was active in the first half of the sixteenth century, supplying the district and helping power mills before returning or distributing water toward the Vega.',
        'Hydraulic regulation demonstrates functional continuity, but the reconstructed branch combines main channel, distributors and outlets whose position and phase require separate verification.',
        'The medieval network continued under Christian regulation and adapted to convents, residences, public spaces and new or reorganised productive uses.',
      ),
      claims: [
        claim('claim.realejo-branch-sixteenth-century-network', 'chronology',
          'Las ordenanzas de aguas de 1538 describen la red de la Acequia Gorda y sus ramales urbanos durante la primera mitad del siglo XVI.',
          'The 1538 water ordinances describe the Acequia Gorda network and its urban branches during the first half of the sixteenth century.',
          'source.ugr-water-ordinances-2022', 'Sistema del Genil, Acequia Gorda y ramales del Realejo', 'Atestigua la operación institucional próxima a 1550.'),
        claim('claim.realejo-branch-mills', 'function',
          'El ramal del Realejo abastecía el barrio y se asociaba a una secuencia de molinos antes de continuar hacia la Vega.',
          'The Realejo branch supplied the district and was associated with a sequence of mills before continuing toward the Vega.',
          'source.ujaen-water-route-2025', 'Apartado sobre la Acequia Gorda y el ramal del Realejo', 'Establece función y corredor general, no la posición de cada derivación.'),
      ],
      relationships: [
        relationship('retains', 'water.acequia-gorda',
          'El ramal formaba parte del sistema de la Acequia Gorda derivado del Genil.',
          'The branch formed part of the Genil-derived Acequia Gorda system.'),
        relationship('routes_toward', 'urban.campo-principe',
          'La distribución atravesaba el Realejo, cuyo nuevo espacio público y edificios alteraron los repartos locales.',
          'Distribution crossed Realejo, where the new public space and buildings altered local allocation.'),
      ],
      geometry_decision: geometry(
        'retain_existing_only_after_audit',
        ['source.ugr-water-ordinances-2022', 'source.ujaen-water-route-2025', 'source.junta-aguado-2009'],
        'La geometría heredada reúne un corredor principal y una salida interpretativa sin distinguir repartidores, molinos y modificaciones del siglo XVI.',
        'The inherited geometry combines a main corridor and an interpreted outlet without distinguishing distributors, mills and sixteenth-century modifications.',
        'Georreferenciar molinos, repartimientos y destinos documentados, asignando fuente y tolerancia a cada tramo antes de reutilizar la red.',
        'Georeference documented mills, allocations and destinations, assigning source and tolerance to each segment before reusing the network.'),
    },
    {
      feature_id: 'route.molinos-sierra-axis',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'probable', change_from_1492: 'retained', physical_state: 'complete',
      },
      content: localized(
        'Camino de los Molinos y la sierra',
        'Corredor meridional entre el Realejo, el Genil, los molinos y Güéjar',
        'Hacia 1550 el corredor de la Puerta de los Molinos probablemente mantenía el acceso desde el Realejo hacia las instalaciones hidráulicas del Genil, las huertas y los caminos de la sierra.',
        'La puerta y la actividad molinera sostienen la continuidad funcional, pero el eje publicado fuera del recinto es interpretativo y no corresponde a una calzada documentada metro a metro.',
        'La ruta heredada mantuvo su papel productivo y territorial mientras cambiaban el Campo del Príncipe, el borde urbano y los puntos de distribución del agua.',
        'Mills and mountain route',
        'Southern corridor between Realejo, the Genil, mills and Güéjar',
        'Around 1550 the corridor through the Mills Gate probably maintained access from Realejo to Genil hydraulic installations, orchards and mountain routes.',
        'The gate and milling activity support functional continuity, but the published axis outside the enclosure is interpretative and not a road documented metre by metre.',
        'The inherited route retained its productive and territorial role while Campo del Príncipe, the urban edge and water-distribution points changed.',
      ),
      claims: [
        claim('claim.molinos-route-gate-continuity', 'chronology',
          'La supervivencia de la Puerta de los Molinos hasta 1833 confirma la continuidad del punto de salida, aunque no del trazado exterior exacto.',
          'The survival of the Mills Gate until 1833 confirms continuity of the exit point, though not of the exact outer route.',
          'source.junta-hoteles-belen-2020', 'Contexto histórico-arqueológico general', 'Aporta un anclaje cronológico y espacial para el corredor.'),
        claim('claim.molinos-route-productive-system', 'function',
          'La red hidráulica del Genil y el Realejo sostenía molinos y usos agrícolas que daban función al corredor meridional en la primera mitad del siglo XVI.',
          'The Genil and Realejo water network supported mills and agricultural uses that gave the southern corridor its function in the first half of the sixteenth century.',
          'source.ugr-water-ordinances-2022', 'Sistema del Genil, Acequia Gorda y ramales meridionales', 'Documenta el sistema productivo, no la huella exacta del camino.'),
      ],
      relationships: [
        relationship('routes_toward', 'gate.molinos',
          'La puerta era el anclaje urbano del camino.',
          'The gate was the urban anchor of the route.'),
        relationship('near', 'water.genil',
          'El corredor descendía hacia los molinos y huertas alimentados por el Genil.',
          'The corridor descended toward mills and orchards supplied by the Genil.'),
      ],
      geometry_decision: geometry(
        'retain_existing_only_after_audit',
        ['source.junta-hoteles-belen-2020', 'source.junta-aguado-2009', 'source.ugr-water-ordinances-2022'],
        'La línea c. 1492 prolonga una dirección funcional sobre vías modernas y no demuestra anchura, bifurcaciones ni continuidad de firme en 1550.',
        'The c. 1492 line extends a functional direction over modern roads and does not establish width, branches or surface continuity in 1550.',
        'Reunir referencias de caminos, molinos, puentes y propiedades, y fijar controles espaciales antes de crear una variante temporal.',
        'Gather references to roads, mills, bridges and properties and establish spatial controls before creating a temporal variant.'),
    },
  ],
})

await writeFile(outputPath, `${JSON.stringify(tranche, null, 2)}\n`, 'utf8')
console.log(`Cuarto tramo de fuentes M10.5 preparado: ${tranche.items.length} entidades; cero geometrías nuevas.`)

function localized(
  esName: string, esFunction: string, esSummary: string, esEvidence: string, esChange: string,
  enName: string, enFunction: string, enSummary: string, enEvidence: string, enChange: string,
) {
  return {
    es: { name: esName, function: esFunction, summary: esSummary, evidence_note: esEvidence, change_note: esChange },
    en: { name: enName, function: enFunction, summary: enSummary, evidence_note: enEvidence, change_note: enChange },
  }
}

function claim(
  claimId: string,
  topic: 'chronology' | 'function' | 'transformation' | 'geometry' | 'interpretation',
  es: string,
  en: string,
  sourceId: string,
  locator: string,
  supports: string,
) {
  return {
    claim_id: claimId,
    topic,
    text: { es, en },
    citations: [{ source_id: sourceId, locator, supports }],
  }
}

function relationship(
  relation: 'adjacent_to' | 'attached_to' | 'contained_by' | 'near' | 'overlaps' | 'part_of_program_with' | 'replaces_function_of' | 'retains' | 'routes_toward' | 'shares_site_with' | 'transformed_from',
  targetId: string,
  es: string,
  en: string,
) {
  return { relation, target_id: targetId, note: { es, en } }
}

function geometry(
  action: 'retain_existing_only_after_audit' | 'create_reference_point_after_site_audit' | 'no_geometry_until_chronology_resolved',
  sourceRefs: string[],
  rationaleEs: string,
  rationaleEn: string,
  conditionEs: string,
  conditionEn: string,
) {
  return {
    status: 'deferred' as const,
    action,
    rationale: { es: rationaleEs, en: rationaleEn },
    release_condition: { es: conditionEs, en: conditionEn },
    source_refs: sourceRefs,
  }
}
