import { writeFile } from 'node:fs/promises'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'
import {
  c1550M10_5SourceReview2Schema,
  M10_5_SOURCE_REVIEW_2_FEATURE_IDS,
} from '../src/data/temporalSchema'

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const outputPath = resolve(repositoryRoot, 'data/research/c1550/m10.5-source-review-2.json')

const tranche = c1550M10_5SourceReview2Schema.parse({
  schema_version: 1,
  milestone: 'M10.5',
  tranche: 'source-review-2',
  period_id: 'c1550',
  status: 'ready_for_content_review',
  public_application_import: false,
  updated_on: '2026-10-02',
  scope_note: 'Diez sistemas heredados de puertas, murallas, agua y circulación preparados para revisión bilingüe; se documenta continuidad desigual sin crear geometría c. 1550.',
  feature_ids: M10_5_SOURCE_REVIEW_2_FEATURE_IDS,
  items: [
    {
      feature_id: 'gate.elvira',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'altered', physical_state: 'complete',
      },
      content: localized(
        'Puerta de Elvira',
        'Acceso noroccidental, control urbano y enlace con la calle Elvira',
        'La puerta-fortaleza seguía siendo una entrada principal hacia 1550 y conservaba un dispositivo mucho mayor que el arco actual, conectado con la calle Elvira y las cercas del Albaicín.',
        'La ficha municipal documenta el complejo y fecha en 1612 la demolición de sus tres barbacanas; esto sostiene su presencia anterior, pero no una planta precisa para 1550.',
        'El acceso islámico continuó dentro de la ciudad cristiana con funciones y símbolos transformados, antes de las grandes demoliciones modernas.',
        'Elvira Gate',
        'North-western entrance, urban control point and link to Elvira Street',
        'The fortified gate remained a principal entrance around 1550 and retained a complex far larger than the present arch, connected to Elvira Street and the Albaicín enclosures.',
        'The municipal record documents the complex and dates demolition of its three barbicans to 1612; this supports earlier presence but not a precise 1550 plan.',
        'The Islamic entrance continued within the Christian city with transformed functions and symbols before the major modern demolitions.',
      ),
      claims: [
        claim('claim.elvira-complex-before-1612', 'chronology',
          'Las tres barbacanas de Puerta Elvira no fueron demolidas hasta 1612, por lo que el complejo anterior seguía materialmente presente hacia 1550.',
          'Elvira Gate’s three barbicans were not demolished until 1612, so the earlier complex remained materially present around 1550.',
          'source.granada-elvira-gate', 'Ficha 22, historia y transformaciones', 'Fecha la demolición principal y documenta la extensión histórica del acceso.'),
        claim('claim.elvira-point-not-complex', 'geometry',
          'El arco conservado y el punto c. 1492 no representan la extensión completa de la puerta-fortaleza de 1550.',
          'The surviving arch and c. 1492 point do not represent the full extent of the fortified gate in 1550.',
          'source.granada-elvira-gate', 'Ficha 22, descripción del dispositivo defensivo', 'Distingue el resto visible del complejo de torres, puertas y barbacanas.'),
      ],
      relationships: [relationship('routes_toward', 'route.elvira-axis',
        'El acceso desembocaba en la calle Elvira y articulaba la llegada a la medina baja.',
        'The entrance opened onto Elvira Street and structured arrival into the lower medina.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.granada-elvira-gate', 'source.ugr-vico-2023'],
        'El punto heredado localiza el acceso, pero oculta el tamaño y la configuración del complejo anterior a 1612.',
        'The inherited point locates the entrance but conceals the size and configuration of the pre-1612 complex.',
        'Contrastar la Plataforma de Vico con la ficha monumental y decidir si c. 1550 requiere punto de sitio o envolvente arqueológica independiente.',
        'Compare the Vico platform with the monument record and decide whether c. 1550 needs a site point or a separate archaeological envelope.'),
    },
    {
      feature_id: 'gate.fajalauza',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'probable', change_from_1492: 'retained', physical_state: 'complete',
      },
      content: localized(
        'Puerta de Fajalauza',
        'Acceso alto del Albaicín hacia Haza Grande y el camino de Guadix',
        'La puerta nazarí continuaba probablemente como paso del recinto en torno a 1550, vinculada al borde del Albaicín y al ámbito alfarero extramuros.',
        'La fábrica conservada, el contexto arqueológico moderno y su representación cartográfica posterior sostienen continuidad, pero no resuelven cada reforma del pasadizo.',
        'El paso mantuvo la relación entre el barrio alto y su exterior, mientras su entorno productivo y su fábrica experimentaban cambios.',
        'Fajalauza Gate',
        'Upper Albaicín entrance towards Haza Grande and the Guadix road',
        'The Nasrid gate probably continued as an enclosure passage around 1550, linked to the Albaicín edge and the extramural pottery area.',
        'The surviving fabric, early-modern archaeological context and later cartographic representation support continuity but do not resolve every alteration to the passage.',
        'The passage retained the relationship between the upper quarter and its exterior while its productive setting and fabric changed.',
      ),
      claims: [
        claim('claim.fajalauza-continuity-probable', 'interpretation',
          'La combinación de fábrica conservada, contexto de época moderna y cartografía de comienzos del XVII hace probable la continuidad de Fajalauza hacia 1550.',
          'The combination of surviving fabric, early-modern context and early seventeenth-century mapping makes Fajalauza’s continuity around 1550 probable.',
          'source.junta-fajalauza-2008', 'Contextualización histórico-arqueológica del área', 'Relaciona la puerta, la cerca, el arrabal y la ocupación moderna del entorno.'),
        claim('claim.fajalauza-fabric-limit', 'geometry',
          'El pasadizo conservado contiene transformaciones y no puede asumirse íntegramente como estado de 1550.',
          'The surviving passage contains transformations and cannot be assumed wholesale as its 1550 state.',
          'source.granada-fajalauza', 'Descripción institucional de la puerta', 'Describe fábrica y localización sin ofrecer una secuencia constructiva fechada.'),
      ],
      relationships: [relationship('attached_to', 'walls.albaicin-north',
        'Fajalauza formaba uno de los accesos de la cerca exterior septentrional del Albaicín.',
        'Fajalauza formed one of the entrances through the Albaicín’s northern outer enclosure.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.granada-fajalauza', 'source.junta-fajalauza-2008', 'source.ugr-vico-2023'],
        'El punto c. 1492 es una buena referencia de sitio, pero todavía no está auditado como variante temporal de 1550.',
        'The c. 1492 point is a useful site reference but has not yet been audited as a 1550 temporal variant.',
        'Revisar la fábrica por fases, la conexión con los lienzos y la representación de Vico antes de reutilizar el punto.',
        'Review fabric phases, wall connections and the Vico representation before reusing the point.'),
    },
    {
      feature_id: 'gate.monaita',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'retained', physical_state: 'unknown',
      },
      content: localized(
        'Puerta Monaita',
        'Acceso heredado de la Alcazaba Qadima dentro del Albaicín',
        'Monaita seguía materialmente presente hacia 1550 como puerta del antiguo recinto zirí, aunque su función cotidiana dentro del Albaicín cristiano y morisco no está aún documentada con precisión.',
        'La fábrica conservada y la destrucción tardía de defensas del entorno sostienen presencia; las fuentes actuales no prueban intensidad de paso ni estado completo.',
        'La puerta fue retenida como elemento material de un recinto interior cuya función defensiva y urbana se transformó después de la conquista.',
        'Monaita Gate',
        'Inherited entrance to the Qadima Citadel within the Albaicín',
        'Monaita remained materially present around 1550 as a gate of the former Zirid enclosure, although its everyday role within the Christian and Morisco Albaicín is not yet precisely documented.',
        'Surviving fabric and the late destruction of surrounding defences support presence; current sources do not establish traffic intensity or complete condition.',
        'The gate was retained as a material element of an inner enclosure whose defensive and urban role changed after the conquest.',
      ),
      claims: [
        claim('claim.monaita-present-before-nineteenth', 'chronology',
          'La puerta sobrevivió hasta las campañas demolicionistas del siglo XIX y, por tanto, estaba materialmente presente en 1550.',
          'The gate survived until nineteenth-century demolition campaigns and was therefore materially present in 1550.',
          'source.granada-monaita', 'Historia y conservación de la puerta', 'Sitúa el riesgo de desaparición en el siglo XIX y documenta la fábrica heredada.'),
        claim('claim.monaita-function-unresolved', 'interpretation',
          'La presencia de la puerta no demuestra que mantuviera en 1550 la misma función defensiva o intensidad de paso que en época islámica.',
          'Presence of the gate does not establish that it retained the same defensive role or traffic intensity in 1550 as in the Islamic period.',
          'source.junta-monaita-wall-2000', 'Lectura arqueológica de puerta y lienzos asociados', 'Distingue conservación material y reconstrucción del funcionamiento histórico.'),
      ],
      relationships: [relationship('attached_to', 'walls.alcazaba-qadima-inner',
        'Monaita pertenecía al recinto interior de la Alcazaba Qadima, no a la cerca exterior tardonazarí.',
        'Monaita belonged to the Qadima Citadel’s inner enclosure rather than the late Nasrid outer wall.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.granada-monaita', 'source.junta-monaita-wall-2000'],
        'El marcador heredado localiza una fábrica conservada, pero necesita una auditoría temporal separada para 1550.',
        'The inherited marker locates surviving fabric but needs a separate temporal audit for 1550.',
        'Confirmar el centro del paso histórico y documentar los lienzos presentes, perdidos y rehechos antes de crear la variante.',
        'Confirm the historical passage centre and document surviving, lost and rebuilt wall sections before creating the variant.'),
    },
    {
      feature_id: 'gate.mawrur',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'unknown', temporal_confidence: 'probable', change_from_1492: 'unknown', physical_state: 'unknown',
      },
      content: localized(
        'Puerta del Mauror — estado c. 1550 no resuelto',
        'Paso desaparecido del recinto interior del Realejo',
        'La Puerta del Sol, de Oriente o del Mauror se sitúa con seguridad en el ámbito de la placeta homónima, pero las fuentes reunidas no prueban todavía su presencia material ni su configuración exacta en 1550.',
        'La toponimia y los estudios de las cercas meridionales fijan el contexto; falta una fuente fechada próxima al corte que describa el vano o su desaparición.',
        'El registro conserva la memoria de un paso islámico dentro del Realejo transformado, sin convertir continuidad toponímica en supervivencia material.',
        'Mauror Gate — unresolved c. 1550 state',
        'Lost passage through the Realejo’s inner enclosure',
        'The Gate of the Sun, Gate of the East or Mauror Gate is securely placed near the eponymous square, but the assembled sources do not yet prove its material presence or exact configuration in 1550.',
        'Toponymy and studies of the southern enclosures establish the context; a source close to the snapshot describing the opening or its disappearance is still missing.',
        'The record preserves memory of an Islamic passage within the transformed Realejo without turning toponymic continuity into material survival.',
      ),
      claims: [
        claim('claim.mawrur-place-aliases', 'function',
          'La placeta de la Puerta del Sol conserva la referencia a la Puerta del Sol, de Oriente o del Mauror.',
          'The Puerta del Sol square preserves reference to the Gate of the Sun, Gate of the East or Mauror Gate.',
          'source.granada-mauror-gate', 'Localización histórica junto al lavadero', 'Relaciona el lugar actual con los tres nombres del paso desaparecido.'),
        claim('claim.mawrur-1550-unresolved', 'interpretation',
          'La identificación del sitio no basta para afirmar que el vano seguía en pie o funcionaba en 1550.',
          'Identification of the site is insufficient to assert that the opening remained standing or operational in 1550.',
          'source.junta-aguado-2009', 'Síntesis de las cercas interiores y exteriores del Realejo', 'El contexto de recinto no aporta una datación suficiente del estado del vano.'),
      ],
      relationships: [relationship('attached_to', 'walls.mauror-realejo-inner',
        'La puerta se asocia a la cerca interior Mauror-Realejo, cuya secuencia debe mantenerse separada del perímetro exterior.',
        'The gate is associated with the Mauror-Realejo inner enclosure, whose sequence must remain separate from the outer perimeter.')],
      geometry_decision: geometry(
        'no_geometry_until_chronology_resolved', ['source.granada-mauror-gate', 'source.junta-aguado-2009', 'source.junta-porteria-santo-domingo-2012'],
        'El punto c. 1492 expresa una localización histórica aproximada, no presencia demostrada en 1550.',
        'The c. 1492 point expresses an approximate historical location, not demonstrated presence in 1550.',
        'Localizar una representación o descripción fechada del paso entre 1540 y comienzos del XVII antes de crear geometría.',
        'Locate a dated depiction or description of the passage between 1540 and the early seventeenth century before creating geometry.'),
    },
    {
      feature_id: 'walls.albaicin-north',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'altered', physical_state: 'partially_in_use',
      },
      content: localized(
        'Cerca septentrional del Albaicín',
        'Límite heredado, discontinuo y progresivamente transformado',
        'La cerca exterior del Albaicín seguía siendo un límite urbano reconocible hacia 1550, con puertas y lienzos presentes, aunque el desmantelamiento posterior a la conquista ya impedía tratarla como un sistema intacto.',
        'Los restos, el recorrido municipal, la arqueología de Fajalauza y la Plataforma de Vico sostienen continuidad desigual; no datan cada segmento.',
        'El recinto pasó de defensa exterior nazarí a borde parcialmente conservado dentro de una ciudad cristiana en transformación.',
        'Northern Albaicín enclosure',
        'Inherited boundary, discontinuous and progressively transformed',
        'The Albaicín outer enclosure remained a recognisable urban boundary around 1550, with gates and wall sections present, although post-conquest dismantling already prevents treating it as an intact system.',
        'Remains, the municipal route, Fajalauza archaeology and the Vico platform support uneven continuity but do not date every segment.',
        'The enclosure shifted from a Nasrid outer defence to a partly surviving edge within a changing Christian city.',
      ),
      claims: [
        claim('claim.albaicin-wall-early-modern-continuity', 'interpretation',
          'La combinación de lienzos conservados, accesos y representación de comienzos del XVII sostiene que amplios sectores de la cerca seguían reconocibles hacia 1550.',
          'The combination of surviving stretches, entrances and early seventeenth-century depiction supports that large parts of the enclosure remained recognisable around 1550.',
          'source.ugr-vico-2023', 'Análisis de la Plataforma y estructura urbana', 'Aporta un control cartográfico temprano posterior para el recinto urbano.'),
        claim('claim.albaicin-wall-not-uniform', 'geometry',
          'La línea c. 1492 no puede reutilizarse como una cerca continua y homogénea de 1550 sin revisar pérdidas, absorciones y reparaciones por tramo.',
          'The c. 1492 line cannot be reused as a continuous, uniform 1550 enclosure without reviewing loss, absorption and repair by segment.',
          'source.granada-albaicin-wall-route', 'Recorrido y conservación de la muralla nazarí', 'Distingue sectores conservados y trazado histórico de conexiones perdidas.'),
      ],
      relationships: [relationship('attached_to', 'gate.fajalauza',
        'La puerta de Fajalauza constituye uno de los controles materiales principales de la cerca septentrional.',
        'Fajalauza Gate forms one of the northern enclosure’s principal material controls.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.granada-albaicin-nasrid-wall', 'source.granada-albaicin-wall-route', 'source.junta-fajalauza-2008', 'source.ugr-vico-2023'],
        'La línea heredada mezcla fábrica conservada, conexiones aproximadas y segmentos sin control temporal independiente.',
        'The inherited line mixes surviving fabric, approximate connections and segments without independent temporal control.',
        'Clasificar cada tramo como presente, perdido antes del corte, probable o desconocido y conservar huecos reales.',
        'Classify each segment as present, lost before the snapshot, probable or unknown and preserve genuine gaps.'),
    },
    {
      feature_id: 'walls.medina-lower',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'altered', physical_state: 'partially_in_use',
      },
      content: localized(
        'Cerca exterior de la ciudad baja',
        'Perímetro compuesto con tramos activos, absorbidos y perdidos',
        'El perímetro tardonazarí seguía estructurando partes de la ciudad baja hacia 1550, pero las expansiones, nuevas instituciones y reformas viarias habían comenzado a absorber o eliminar sectores.',
        'La arqueología y la cartografía temprana confirman el sistema general con conservación desigual; la fecha de cada tramo meridional no está resuelta.',
        'La cerca dejó de ser un borde defensivo uniforme y pasó a convivir con la expansión cristiana y la reutilización parcelaria.',
        'Outer enclosure of the lower city',
        'Composite perimeter with active, absorbed and lost stretches',
        'The late Nasrid perimeter still structured parts of the lower city around 1550, but expansion, new institutions and street reforms had begun to absorb or remove sections.',
        'Archaeology and early mapping confirm the general system with uneven survival; the date of each southern stretch remains unresolved.',
        'The wall ceased to be a uniform defensive edge and coexisted with Christian expansion and parcel reuse.',
      ),
      claims: [
        claim('claim.lower-wall-composite-presence', 'interpretation',
          'La cartografía temprana y los anclajes arqueológicos sostienen la presencia de un perímetro compuesto, no la continuidad de todos sus segmentos en 1550.',
          'Early mapping and archaeological anchors support presence of a composite perimeter, not continuity of every segment in 1550.',
          'source.granada-centre-plan', 'Memoria histórica y restos del recinto de la medina', 'Identifica anclajes y pérdidas dentro del perímetro urbano histórico.'),
        claim('claim.lower-wall-segment-audit', 'geometry',
          'Los tramos occidentales y meridionales requieren datación individual antes de trasladar la línea c. 1492 al nuevo periodo.',
          'Western and southern stretches require individual dating before transferring the c. 1492 line into the new period.',
          'source.junta-aguado-2009', 'Distinción de cercas interiores y exterior meridional', 'Muestra que el perímetro publicado integra recintos y reconstrucciones diferentes.'),
      ],
      relationships: [relationship('attached_to', 'gate.elvira',
        'Puerta Elvira es uno de los anclajes seguros del perímetro noroccidental de la ciudad baja.',
        'Elvira Gate is one of the secure anchors for the lower city’s north-western perimeter.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.granada-centre-plan', 'source.junta-western-wall-2006', 'source.junta-aguado-2009', 'source.ugr-vico-2023'],
        'La línea c. 1492 sintetiza un perímetro útil, pero no distingue la supervivencia temporal de cada segmento hacia 1550.',
        'The c. 1492 line synthesises a useful perimeter but does not distinguish each segment’s survival around 1550.',
        'Crear una matriz por segmentos con fuente, intervalo, estado, confianza y relación con nuevas obras antes de derivar la variante.',
        'Create a segment matrix with source, date range, state, confidence and relationship to new works before deriving the variant.'),
    },
    {
      feature_id: 'water.acequia-aynadamar',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'retained', physical_state: 'complete',
      },
      content: localized(
        'Acequia de Aynadamar en la Granada de 1538',
        'Abastecimiento regulado del Albaicín y la Alcazaba',
        'Aynadamar continuaba activa en la primera mitad del siglo XVI, llevando agua a aljibes, casas, huertas y grandes propiedades del Albaicín y la Alcazaba bajo un reparto municipal detallado.',
        'Las Ordenanzas confirman función y usuarios; el trazado publicado combina reconstrucción medieval, restos y controles posteriores y necesita auditoría por ramal.',
        'El sistema hidráulico heredado mantuvo su función esencial mientras su administración y algunos componentes se adaptaban al gobierno cristiano.',
        'Aynadamar Canal in the Granada of 1538',
        'Regulated supply for the Albaicín and the Citadel',
        'Aynadamar remained active in the first half of the sixteenth century, carrying water to cisterns, houses, orchards and major properties in the Albaicín and the Citadel under detailed municipal allocation.',
        'The Ordinances confirm function and users; the published route combines medieval reconstruction, remains and later controls and needs branch-by-branch audit.',
        'The inherited hydraulic system retained its essential role while its administration and some components adapted to Christian government.',
      ),
      claims: [
        claim('claim.aynadamar-1538-supply', 'function',
          'Las Ordenanzas de las Aguas documentan que Aynadamar abastecía aljibes, viviendas, huertas y propiedades del Albaicín y la Alcazaba.',
          'The Water Ordinances document that Aynadamar supplied cisterns, houses, orchards and properties in the Albaicín and the Citadel.',
          'source.ugr-water-ordinances-2022', 'Apartado 2.2, acequia de Aynadamar o de Alfacar', 'Documenta usos, beneficiarios y distribución del agua en la primera mitad del XVI.'),
        claim('claim.aynadamar-route-limit', 'geometry',
          'La continuidad funcional no demuestra que todos los ramales representados para 1492 conservaran idéntico trazado en 1550.',
          'Functional continuity does not show that every branch represented for 1492 retained an identical course in 1550.',
          'source.junta-fajalauza-2008', 'Resultados y contexto hidráulico de Cruz de Piedra', 'Aporta un control arqueológico puntual de un ramal, no una red urbana completa.'),
      ],
      relationships: [relationship('routes_toward', 'urban.albaicin',
        'La conducción entraba en la ciudad alta y distribuía agua entre el Albaicín y la Alcazaba.',
        'The conduit entered the upper city and distributed water across the Albaicín and the Citadel.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.ugr-water-ordinances-2022', 'source.ujaen-water-route-2025', 'source.junta-fajalauza-2008'],
        'La línea c. 1492 identifica el sistema, pero no separa ramales confirmados por las Ordenanzas de los inferidos desde cartografía posterior.',
        'The c. 1492 line identifies the system but does not separate branches confirmed by the Ordinances from those inferred from later mapping.',
        'Relacionar cada topónimo y usuario de 1538 con ramales auditables y marcar finales, derivaciones y tramos subterráneos desconocidos.',
        'Relate each 1538 place and user to auditable branches and mark unknown endpoints, diversions and underground stretches.'),
    },
    {
      feature_id: 'water.acequia-gorda',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'retained', physical_state: 'complete',
      },
      content: localized(
        'Acequia Gorda y derivaciones del Genil',
        'Sistema de riego, molinos y abastecimiento meridional',
        'El sistema derivado del Genil seguía activo en la primera mitad del siglo XVI; su ramal del Realejo abastecía el barrio y movía numerosos molinos antes de reincorporarse a la red.',
        'La regulación documenta función y organización, pero el corredor c. 1492 sintetiza un cauce principal y derivaciones que deben distinguirse temporalmente.',
        'La infraestructura medieval fue retenida por su valor productivo y urbano, aunque reparto, administración y ramales evolucionaron.',
        'Acequia Gorda and the Genil branches',
        'Irrigation, mills and southern urban supply system',
        'The Genil-derived system remained active in the first half of the sixteenth century; its Realejo branch supplied the quarter and powered numerous mills before rejoining the network.',
        'The regulations document function and organisation, but the c. 1492 corridor synthesises a main channel and branches that must be distinguished temporally.',
        'The medieval infrastructure was retained for its productive and urban value, although allocation, administration and branches evolved.',
      ),
      claims: [
        claim('claim.gorda-realejo-branch-1538', 'function',
          'Las Ordenanzas describen la acequia del Realejo como ramal de la Acequia Gorda del Genil, asociado al abastecimiento y a molinos.',
          'The Ordinances describe the Realejo canal as a branch of the Genil’s Acequia Gorda, associated with supply and mills.',
          'source.ugr-water-ordinances-2022', 'Apartado 2.1 y nota 36, ramal del Realejo', 'Relaciona el ramal urbano con el sistema de Gorda y su función productiva.'),
        claim('claim.gorda-network-limit', 'geometry',
          'El funcionamiento del sistema no autoriza a copiar como una sola línea todos los repartidores y derivaciones reconstruidos para 1492.',
          'Operation of the system does not authorise copying all distributors and reconstructed 1492 branches as a single line.',
          'source.ujaen-water-route-2025', 'Mapa 5 y síntesis de Gorda y sus derivaciones', 'Distingue cauce principal y repartimientos dentro de una reconstrucción histórica amplia.'),
      ],
      relationships: [relationship('part_of_program_with', 'water.acequia-realejo',
        'El ramal del Realejo formaba parte del sistema derivado de Gorda y debe conservarse como entidad relacionada, no fusionada.',
        'The Realejo branch formed part of the Gorda-derived system and should remain a related, not merged, entity.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.ugr-water-ordinances-2022', 'source.ujaen-water-route-2025'],
        'La línea heredada ofrece el corredor general, pero no acredita por separado estado, ancho, derivaciones y repartidores en 1550.',
        'The inherited line provides the general corridor but does not separately establish state, width, branches and distributors in 1550.',
        'Separar cauce principal, Realejo y demás derivaciones y vincular cada segmento a la ordenanza o evidencia cartográfica correspondiente.',
        'Separate the main channel, Realejo and other branches and link each segment to the corresponding ordinance or cartographic evidence.'),
    },
    {
      feature_id: 'water.darro',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'retained', physical_state: 'complete',
      },
      content: localized(
        'Río Darro',
        'Cauce urbano, fuente de acequias y receptor de desagües',
        'El Darro continuaba atravesando Granada y alimentando una red de acequias en la primera mitad del siglo XVI, mientras las obras de Plaza Nueva modificaban localmente su relación con la ciudad.',
        'La presencia y función hidráulica son seguras; el eje moderno bajo Reyes Católicos corresponde al gran embovedado del siglo XIX y no debe proyectarse sin auditoría.',
        'El río conservó su papel estructural, aunque puentes, plataformas, vertidos y cubrimientos parciales transformaron segmentos urbanos concretos.',
        'River Darro',
        'Urban channel, source of canals and recipient of drainage',
        'The Darro continued through Granada and fed a canal network in the first half of the sixteenth century while Plaza Nueva works locally changed its relationship with the city.',
        'Its presence and hydraulic role are secure; the modern axis beneath Reyes Católicos belongs to the major nineteenth-century vault and must not be projected without audit.',
        'The river retained its structural role while bridges, platforms, waste and partial coverings transformed particular urban segments.',
      ),
      claims: [
        claim('claim.darro-sixteenth-century-network', 'function',
          'En la primera mitad del siglo XVI el Darro atravesaba la ciudad y alimentaba varias acequias y ramales de abastecimiento y desagüe.',
          'In the first half of the sixteenth century the Darro crossed the city and fed several supply and drainage canals and branches.',
          'source.ugr-water-ordinances-2022', 'Apartados 2.1 y 3, acequias del Darro y desagüe', 'Documenta el río y la red regulada dependiente de sus aguas.'),
        claim('claim.darro-modern-vault-limit', 'geometry',
          'El embovedado continuo bajo Reyes Católicos es principalmente una obra de 1854–1884 y no representa automáticamente el cauce de 1550.',
          'The continuous vault beneath Reyes Católicos is chiefly a work of 1854–1884 and does not automatically represent the 1550 channel.',
          'source.junta-darro-reyes-catolicos', 'Intervención y contextualización del embovedado de 1858', 'Fecha la gran transformación moderna y sus muros laterales.'),
      ],
      relationships: [relationship('adjacent_to', 'route.darro-axis',
        'La Carrera y el eje del Darro compartían el corredor oriental, pero no deben confundirse cauce, ribera y calle.',
        'The Carrera and Darro axis shared the eastern corridor, but channel, riverbank and street must not be conflated.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.ugr-water-ordinances-2022', 'source.granada-carrera-darro', 'source.junta-darro-reyes-catolicos'],
        'La línea c. 1492 combina eje natural visible y referencia moderna del tramo cubierto, con posibles rectificaciones locales.',
        'The c. 1492 line combines the visible natural axis and a modern reference for the covered stretch, with possible local realignments.',
        'Separar cauce visible, cubrimiento de Plaza Nueva y tramos posteriormente embovedados, documentando puentes y tolerancia por segmento.',
        'Separate visible channel, Plaza Nueva covering and later vaulted stretches, documenting bridges and segment-level tolerance.'),
    },
    {
      feature_id: 'route.elvira-axis',
      cluster: 'inherited_systems',
      readiness: 'ready_for_content_review',
      period_assessment: {
        presence: 'present', temporal_confidence: 'secure', change_from_1492: 'retained', physical_state: 'complete',
      },
      content: localized(
        'Eje de Elvira',
        'Corredor histórico entre Puerta Elvira y el centro urbano',
        'La calle Elvira conservaba hacia 1550 el corredor que enlazaba la puerta noroccidental con el corazón de la ciudad, aunque sus extremos y frentes se adaptaban a la nueva organización cristiana.',
        'La continuidad del eje está respaldada por la puerta, la morfología y la cartografía temprana; anchura y alineaciones exactas requieren regresión documental.',
        'El eje islámico fue retenido como calle urbana y comercial, con transformaciones locales que no justifican una línea idéntica a la actual.',
        'Elvira axis',
        'Historical corridor between Elvira Gate and the urban centre',
        'Around 1550 Elvira Street retained the corridor linking the north-western gate with the heart of the city, although its ends and frontages adapted to the new Christian organisation.',
        'Continuity of the axis is supported by the gate, morphology and early mapping; exact width and alignments require documentary regression.',
        'The Islamic axis was retained as an urban and commercial street, with local changes that do not justify a line identical to today’s.',
      ),
      claims: [
        claim('claim.elvira-axis-historic-corridor', 'function',
          'La calle Elvira fue uno de los ejes históricos principales y conectaba el centro urbano con Puerta Elvira.',
          'Elvira Street was one of the principal historical axes and connected the urban centre with Elvira Gate.',
          'source.granada-calle-elvira', 'Descripción histórica y función comercial', 'Identifica el corredor y su papel dentro de la estructura urbana histórica.'),
        claim('claim.elvira-axis-alignment-limit', 'geometry',
          'La continuidad del corredor no demuestra que anchura, frentes y extremos fueran idénticos a los actuales en 1550.',
          'Continuity of the corridor does not show that its width, frontages and ends were identical to those of today in 1550.',
          'source.ugr-vico-2023', 'Análisis urbanístico de la Plataforma', 'Proporciona un control temprano posterior, no una alineación métrica de 1550.'),
      ],
      relationships: [relationship('routes_toward', 'gate.elvira',
        'El corredor desembocaba en Puerta Elvira y vinculaba la medina con las salidas noroccidentales.',
        'The corridor reached Elvira Gate and linked the medina with the north-western approaches.')],
      geometry_decision: geometry(
        'retain_existing_only_after_audit', ['source.granada-calle-elvira', 'source.granada-elvira-gate', 'source.ugr-vico-2023'],
        'La línea c. 1492 generaliza el eje sobre la calle moderna y no representa cambios de anchura, frentes o conexiones.',
        'The c. 1492 line generalises the axis over the modern street and does not represent changes in width, frontages or connections.',
        'Comparar la Plataforma, parcelario y obras documentadas por segmentos antes de crear una línea temporal c. 1550.',
        'Compare the Platform, parcels and documented works by segment before creating a c. 1550 temporal line.'),
    },
  ],
})

await writeFile(outputPath, `${JSON.stringify(tranche, null, 2)}\n`, 'utf8')
console.log(`Segundo tramo de fuentes M10.5 preparado: ${tranche.items.length} sistemas heredados; cero geometrías nuevas.`)

function localized(
  esName: string, esFunction: string, esSummary: string, esEvidence: string, esChange: string,
  enName: string, enFunction: string, enSummary: string, enEvidence: string, enChange: string,
) {
  return {
    es: { name: esName, function: esFunction, summary: esSummary, evidence_note: esEvidence, change_note: esChange },
    en: { name: enName, function: enFunction, summary: enSummary, evidence_note: enEvidence, change_note: enChange },
  }
}

function claim(
  claimId: string,
  topic: 'chronology' | 'function' | 'transformation' | 'geometry' | 'interpretation',
  es: string,
  en: string,
  sourceId: string,
  locator: string,
  supports: string,
) {
  return {
    claim_id: claimId,
    topic,
    text: { es, en },
    citations: [{ source_id: sourceId, locator, supports }],
  }
}

function relationship(
  relation: 'adjacent_to' | 'attached_to' | 'contained_by' | 'near' | 'overlaps' | 'part_of_program_with' | 'replaces_function_of' | 'retains' | 'routes_toward' | 'shares_site_with' | 'transformed_from',
  targetId: string,
  es: string,
  en: string,
) {
  return { relation, target_id: targetId, note: { es, en } }
}

function geometry(
  action: 'retain_existing_only_after_audit' | 'create_reference_point_after_site_audit' | 'no_geometry_until_chronology_resolved',
  sourceRefs: string[],
  rationaleEs: string,
  rationaleEn: string,
  conditionEs: string,
  conditionEn: string,
) {
  return {
    status: 'deferred' as const,
    action,
    rationale: { es: rationaleEs, en: rationaleEn },
    release_condition: { es: conditionEs, en: conditionEn },
    source_refs: sourceRefs,
  }
}
